version: "3.8"
services:
  dex-service:
    image: ghcr.io/dexidp/dex:v2.32.0
    container_name: dex-service
    volumes:
    - ./config-ldap.yaml:/etc/dex/config.docker.yaml
    ports:
      - 5556:5556
    networks:
      - dex
  ldap-service:
    image: bitnami/openldap:2.6.4-debian-11-r4
    environment:
      LDAP_TLS_VERIFY_CLIENT: try
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_ROOT: "dc=example,dc=org"
      LDAP_CUSTOM_LDIF_DIR: "/ldifs"
    volumes:
    - ./config-ldap.ldif:/ldifs/config-ldap.ldif
    ports:
    - 1389:1389
    networks:
      - dex

networks:
  dex:
    name: dex

volumes:
  data1-1: