schemaVersion: 2.1.0
metadata:
  name: terrakube-platform
components:

  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-c63ad83
      memoryLimit: 8Gi
      mountSources: true
      endpoints:
        - exposure: public
          name: terrakube-api
          protocol: http
          targetPort: 8080
        - exposure: public
          name: terrakube-registry
          protocol: http
          targetPort: 8075
        - exposure: public
          name: terrakube-executor
          protocol: http
          targetPort: 8090
        - exposure: public
          name: terrakube-ui
          protocol: http
          targetPort: 3000
        - exposure: public
          name: terrakube-dex
          protocol: http
          targetPort: 5556
      volumeMounts:
        - name: m2
          path: /home/user/.m2

  - name: m2
    volume:
      size: 5G

commands:
  - id: maven-build
    exec:
      component: maven
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        bash /projects/terrakube/scripts/che/buildApi.sh
      group:
        kind: build
        isDefault: false
