schemaVersion: 2.1.0
metadata:
  name: python-hello-world
attributes:
  che-theia.eclipse.org/sidecar-policy: USE_DEV_CONTAINER
components:
  - name: python
    container:
      image: quay.io/minio/minio:latest
      memoryLimit: 512Mi
      mountSources: true
  - name: venv
    volume:
      size: 1G