schemaVersion: 2.2.0
metadata:
  name: terrakube-project
components:
  - name: go
    container:
      image: golang
      memoryLimit: 512Mi
      mountSources: false
      command: ['sleep', 'infinity']
      env:
        - name: gopath
          value: $(PROJECTS_ROOT)/go
        - name: gocache
          value: /tmp/go-cache
      endpoints:
        - name: web
          targetPort: 8080
          exposure: public