schemaVersion: 2.1.0
metadata:
  name: python-hello-world
attributes:
  che-theia.eclipse.org/sidecar-policy: USE_DEV_CONTAINER
components:
  - name: python
    container:
      image: quay.io/devfile/base-developer-image:ubi8-7bd4fe3
      volumeMounts:
        - name: venv
          path: /home/user/.venv
      memoryLimit: 512Mi
      mountSources: true
  - name: venv
    volume:
      size: 1G