schemaVersion: 2.2.0
metadata:
  name: terrakube-project
components:
  - name: minio
    container:
      image: quay.io/minio/minio:latest
      memoryLimit: 512Mi
      #mountSources: true
      env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin
        - name: MINIO_DEFAULT_BUCKETS
          value: sample
      endpoints:
        - name: minio-server
          targetPort: 9000
          protocol: https
          secure: true
          exposure: public
      volumeMounts:
        - name: miniovol
          path: /data
  - name: miniovol
    volume:
      size: 256Mi
commands:
  - id: min-io
    exec:
      component: minio
      commandLine: 'minio server'
      #workingDir: '${PROJECTS_ROOT}/src/github.com/acme/my-go-project'