version: "3"
services:
  terrakube-api:
    image: api-server:2.12.0
    ports: 
    - 8080:8080
    env_file:
      - api.env
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.42
    ports:
    - 6831:6831/udp
    - 6832:6832/udp
    - 16686:16686
    - 14268:14268
    - 14250:14250