version: "3.8"
services:
  minio-service:
    image: quay.io/minio/minio:RELEASE.2022-09-22T18-57-27Z
    command: server /data --console-address ":9001"
    expose:
      - 8000:8000
      - 8001:8001
    volumes:
      - data1-1:/data
    networks:
      - minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: "https://9001-azbuilder-terrakube-wgh07jmpo99.ws-us67.gitpod.io"
      MINIO_SERVER_URL: "https://9000-azbuilder-terrakube-wgh07jmpo99.ws-us67.gitpod.io"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  minio:
    name: minio  
volumes:
  data1-1: