name: Push Docker Images

on: 
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
       VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build Image with Maven
      run: mvn -pl "api,registry,executor" spring-boot:build-image -B  --file pom.xml -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Add Git to Executor
      run: docker run --user="root" --entrypoint launcher $(docker images executor -q) "apt-get update && apt-get install git -y"

    - name: Restore default user and entrypoint
      run: docker commit --change='ENTRYPOINT ["/cnb/process/web"]' --change='USER cnb' $(docker ps -lq) executortemp
    
    - name: Docker tag API Image 
      run: docker tag $(docker images api-server -q) azbuilder/api-server:$VERSION
      
    - name: Docker tag API Image latest
      run: docker tag $(docker images api-server -q) azbuilder/api-server:latest
    
    - name: Docker Push API latest
      run: docker push azbuilder/api-server:$VERSION
      
    - name: Docker Push API latest
      run: docker push azbuilder/api-server:latest

    - name: Docker tag Registry Image
      run: docker tag $(docker images open-registry -q) azbuilder/open-registry:$VERSION

    - name: Docker tag Registry Image latest
      run: docker tag $(docker images open-registry -q) azbuilder/open-registry:latest

    - name: Docker Push Registry
      run: docker push azbuilder/open-registry:$VERSION

    - name: Docker Push Registry latest
      run: docker push azbuilder/open-registry:latest

    - name: Docker tag EXECUTOR Image
      run: docker tag $(docker images executortemp -q) azbuilder/executor:$VERSION

    - name: Docker tag EXECUTOR Image latest
      run: docker tag $(docker images executortemp -q) azbuilder/executor:latest

    - name: Docker Push EXECUTOR latest
      run: docker push azbuilder/executor:$VERSION

    - name: Docker Push EXECUTOR latest
      run: docker push azbuilder/executor:latest
      
    - name: Docker tag UI Image 
      run: docker tag $(docker images terrakube-ui -q) azbuilder/terrakube-ui:$VERSION

    - name: Docker tag UI Image latest
      run: docker tag $(docker images terrakube-ui -q) azbuilder/terrakube-ui:latest

    - name: Docker Push UI Version
      run: docker push azbuilder/terrakube-ui:$VERSION

    - name: Docker Push UI Latest
      run: docker push azbuilder/terrakube-ui:latest
